import type { Frequency, RecurringConfig, Transaction } from '../types'

const RECURRING_FREQUENCIES: Exclude<Frequency, 'none'>[] = ['daily', 'weekly', 'monthly', 'yearly']

function normalizeInterval(recurring: RecurringConfig): number {
  return Math.max(1, recurring.interval ?? 1)
}

export function isRecurringFrequency(frequency: Frequency): frequency is Exclude<Frequency, 'none'> {
  return RECURRING_FREQUENCIES.includes(frequency as Exclude<Frequency, 'none'>)
}

export function getNextDate(date: Date | string, recurring: RecurringConfig): Date {
  const next = new Date(date)
  const interval = normalizeInterval(recurring)

  switch (recurring.frequency) {
    case 'daily':
      next.setDate(next.getDate() + interval)
      break
    case 'weekly':
      next.setDate(next.getDate() + (7 * interval))
      break
    case 'monthly':
      next.setMonth(next.getMonth() + interval)
      break
    case 'yearly':
      next.setFullYear(next.getFullYear() + interval)
      break
  }

  return next
}

function startOfDay(date: Date | string): Date {
  const value = new Date(date)
  value.setHours(0, 0, 0, 0)
  return value
}

function sameDay(a: Date | string, b: Date | string): boolean {
  return startOfDay(a).getTime() === startOfDay(b).getTime()
}

function makeOccurrenceId(recurringId: string, date: Date): string {
  return `rec-${recurringId}-${date.toISOString()}`
}

function hasOccurrenceForDate(expenses: Transaction[], recurringId: string, date: Date): boolean {
  return expenses.some((expense) => {
    if (!sameDay(expense.date, date)) return false
    if (expense.parentRecurringId === recurringId) return true
    if (expense.recurring?.id === recurringId) return true
    return false
  })
}

function buildGeneratedExpense(template: Transaction, recurring: RecurringConfig, date: Date): Transaction {
  return {
    id: makeOccurrenceId(recurring.id, date),
    name: template.name,
    amount: template.amount,
    type: template.type,
    category: template.category,
    frequency: recurring.frequency,
    date,
    notes: template.notes,
    account: template.account,
    emoji: template.emoji,
    isAutoGenerated: true,
    parentRecurringId: recurring.id,
    createdAt: new Date(),
  }
}

export function createRecurringConfig(
  frequency: Exclude<Frequency, 'none'>,
  startDate: Date,
  previous?: RecurringConfig
): RecurringConfig {
  return {
    id: previous?.id ?? crypto.randomUUID(),
    frequency,
    interval: previous?.interval ?? 1,
    startDate: previous?.startDate ?? startDate.toISOString(),
    endDate: previous?.endDate,
    lastGeneratedAt: previous?.lastGeneratedAt ?? startDate.toISOString(),
    autoAdd: previous?.autoAdd ?? true,
  }
}

export function generateRecurringExpenses(expenses: Transaction[], now = new Date()): Transaction[] {
  const updated = [...expenses]

  for (const expense of expenses) {
    const recurring = expense.recurring
    if (!recurring || recurring.autoAdd === false) continue

    const endDate = recurring.endDate ? startOfDay(recurring.endDate) : null
    let cursor = recurring.lastGeneratedAt
      ? new Date(recurring.lastGeneratedAt)
      : new Date(recurring.startDate)

    let nextDate = getNextDate(cursor, recurring)
    let lastGeneratedAt = cursor

    while (startOfDay(nextDate) <= startOfDay(now)) {
      if (endDate && startOfDay(nextDate) > endDate) break

      if (!hasOccurrenceForDate(updated, recurring.id, nextDate)) {
        updated.push(buildGeneratedExpense(expense, recurring, new Date(nextDate)))
      }

      lastGeneratedAt = new Date(nextDate)
      nextDate = getNextDate(nextDate, recurring)
    }

    if (lastGeneratedAt.getTime() !== cursor.getTime()) {
      expense.recurring = {
        ...recurring,
        lastGeneratedAt: lastGeneratedAt.toISOString(),
      }
    }
  }

  return updated.sort((a, b) => b.date.getTime() - a.date.getTime())
}
