import { createContext, useContext, useState, useEffect, useCallback, useRef, type ReactNode } from 'react'
import { useUser } from '@clerk/clerk-react'
import { supabase } from '../lib/supabase'
import type { Transaction, Budget, Insight, RecurringConfig, Frequency } from '../types'
import { useInsights } from '../hooks/useInsights'
import { createRecurringConfig, generateRecurringExpenses, getNextDate, isRecurringFrequency } from '../utils/recurring'

// ─── Types ────────────────────────────────────────────────────────────────────
interface PendingDeletion {
  transaction: Transaction
  expiresAt: number
}

interface ExpenseContextType {
  transactions: Transaction[]
  budget: Budget | null
  setBudget: (b: Budget | null) => void
  balance: number
  isLoading: boolean
  isOffline: boolean
  addTransaction: (t: Omit<Transaction, 'id' | 'createdAt'>) => Promise<void>
  deleteTransaction: (id: string, mode?: 'single' | 'stop-recurring') => Promise<void>
  updateTransaction: (id: string, updates: Partial<Transaction>, scope?: 'single' | 'future') => Promise<void>
  fetchTransactions: () => Promise<void>
  pendingDeletion: PendingDeletion | null
  undoDelete: () => void
  insights: Insight[]
  activeInsights: Insight[]
  dismissInsight: (id: string) => void
  checkRealtimeTriggers: (newTx: Transaction, allTxns: Transaction[]) => Promise<void>
}

const ExpenseContext = createContext<ExpenseContextType | null>(null)

const UNDO_WINDOW_MS = 5000

function deserializeRecurring(value: unknown): RecurringConfig | undefined {
  if (!value) return undefined
  if (typeof value === 'string') {
    try {
      return JSON.parse(value) as RecurringConfig
    } catch {
      return undefined
    }
  }
  if (typeof value === 'object') return value as RecurringConfig
  return undefined
}

function serializeRecurring(recurring?: RecurringConfig | null) {
  return recurring ?? null
}

function cloneTransaction(transaction: Transaction): Transaction {
  return {
    ...transaction,
    date: new Date(transaction.date),
    createdAt: new Date(transaction.createdAt),
    recurring: transaction.recurring ? { ...transaction.recurring } : undefined,
  }
}

function sortTransactions(items: Transaction[]): Transaction[] {
  return [...items].sort((a, b) => b.date.getTime() - a.date.getTime())
}

// ─── Row mappers ──────────────────────────────────────────────────────────────
function rowToTransaction(row: Record<string, unknown>): Transaction {
  return {
    id: row.id as string,
    name: row.name as string,
    amount: Number(row.amount),
    type: row.type as Transaction['type'],
    category: (row.category as string) ?? null,
    frequency: (row.frequency as Transaction['frequency']) ?? 'none',
    date: new Date(row.date as string),
    notes: (row.notes as string) ?? '',
    account: (row.account as string) ?? undefined,
    emoji: (row.emoji as string) ?? '💳',
    recurring: deserializeRecurring(row.recurring),
    isAutoGenerated: Boolean(row.is_auto_generated),
    parentRecurringId: (row.parent_recurring_id as string) ?? undefined,
    createdAt: new Date(row.created_at as string),
  }
}

function transactionToInsertRow(userId: string, transaction: Omit<Transaction, 'id' | 'createdAt'>) {
  return {
    user_id: userId,
    name: transaction.name,
    amount: transaction.amount,
    type: transaction.type,
    category: transaction.category ?? null,
    frequency: transaction.frequency,
    date: transaction.date.toISOString(),
    notes: transaction.notes ?? '',
    account: transaction.account ?? null,
    emoji: transaction.emoji,
    ...(transaction.recurring ? { recurring: serializeRecurring(transaction.recurring) } : {}),
    ...(transaction.isAutoGenerated ? { is_auto_generated: true } : {}),
    ...(transaction.parentRecurringId ? { parent_recurring_id: transaction.parentRecurringId } : {}),
    last_logged_at: transaction.date.toISOString(),
  }
}

function transactionToLegacyInsertRow(userId: string, transaction: Omit<Transaction, 'id' | 'createdAt'>) {
  return {
    user_id: userId,
    name: transaction.name,
    amount: transaction.amount,
    type: transaction.type,
    category: transaction.category ?? null,
    frequency: transaction.frequency,
    date: transaction.date.toISOString(),
    notes: transaction.notes ?? '',
    account: transaction.account ?? null,
    emoji: transaction.emoji,
    last_logged_at: transaction.date.toISOString(),
  }
}

function isMissingRecurringSchemaError(error: unknown): boolean {
  if (!error || typeof error !== 'object') return false
  const details = JSON.stringify(error).toLowerCase()
  return (
    details.includes('recurring') ||
    details.includes('is_auto_generated') ||
    details.includes('parent_recurring_id')
  )
}

function transactionUpdatesToRow(updates: Partial<Transaction>) {
  const row: Record<string, unknown> = {}
  if ('name' in updates) row.name = updates.name
  if ('amount' in updates) row.amount = updates.amount
  if ('type' in updates) row.type = updates.type
  if ('category' in updates) row.category = updates.category ?? null
  if ('frequency' in updates) row.frequency = updates.frequency
  if ('date' in updates && updates.date) row.date = updates.date.toISOString()
  if ('notes' in updates) row.notes = updates.notes
  if ('account' in updates) row.account = updates.account ?? null
  if ('emoji' in updates) row.emoji = updates.emoji
  if ('recurring' in updates) row.recurring = serializeRecurring(updates.recurring ?? null)
  if ('isAutoGenerated' in updates) row.is_auto_generated = updates.isAutoGenerated ?? false
  if ('parentRecurringId' in updates) row.parent_recurring_id = updates.parentRecurringId ?? null
  return row
}

function rowToBudget(row: Record<string, unknown>): Budget {
  return {
    id: row.id as string,
    amount: Number(row.amount),
    period: row.period as Budget['period'],
    period_start_day: Number(row.period_start_day),
    alert_threshold: Number(row.alert_threshold),
    alert_fired_at: row.alert_fired_at ? new Date(row.alert_fired_at as string) : null,
    notifications_enabled: Boolean(row.notifications_enabled),
    count_income: Boolean(row.count_income),
    rollover_enabled: Boolean(row.rollover_enabled),
    created_at: new Date(row.created_at as string),
    updated_at: new Date(row.updated_at as string),
  }
}

// ─── Provider ─────────────────────────────────────────────────────────────────
export function ExpenseProvider({ children }: { children: ReactNode }) {
  const { user } = useUser()
  const userId = user?.id ?? null

  const [transactions, setTransactions] = useState<Transaction[]>([])
  const [budget, setBudgetState] = useState<Budget | null>(null)
  const [isLoading, setIsLoading] = useState(true)
  const [isOffline, setIsOffline] = useState(!navigator.onLine)
  const [pendingDeletion, setPendingDeletion] = useState<PendingDeletion | null>(null)
  const undoTimerRef = useRef<number | null>(null)
  const pendingDeleteRef = useRef<{ id: string; timer: number } | null>(null)
  const recurringSyncRef = useRef(false)

  const { insights, activeInsights, dismissInsight, checkRealtimeTriggers, resetBudgetThresholds } =
    useInsights(transactions, budget)

  // ── Online/offline tracking ──
  useEffect(() => {
    const onOnline = () => setIsOffline(false)
    const onOffline = () => setIsOffline(true)
    window.addEventListener('online', onOnline)
    window.addEventListener('offline', onOffline)
    return () => {
      window.removeEventListener('online', onOnline)
      window.removeEventListener('offline', onOffline)
    }
  }, [])

  // ── Fetch transactions ──
  const syncRecurringTransactions = useCallback(async (source: Transaction[]) => {
    if (!userId || recurringSyncRef.current) return

    const workingCopy = source.map(cloneTransaction)
    const generated = generateRecurringExpenses(workingCopy)
    const generatedIds = new Set(source.map((item) => item.id))
    const missingGenerated = generated.filter((item) => item.isAutoGenerated && !generatedIds.has(item.id))
    const templateUpdates = generated
      .filter((item) => item.recurring)
      .filter((item) => {
        const original = source.find((existing) => existing.id === item.id)
        return original?.recurring?.lastGeneratedAt !== item.recurring?.lastGeneratedAt
      })

    if (missingGenerated.length === 0 && templateUpdates.length === 0) return

    recurringSyncRef.current = true
    setTransactions(generated)

    try {
      if (missingGenerated.length > 0) {
        const { error } = await supabase
          .from('transactions')
          .insert(missingGenerated.map((transaction) => transactionToInsertRow(userId, {
            name: transaction.name,
            amount: transaction.amount,
            type: transaction.type,
            category: transaction.category,
            frequency: transaction.frequency,
            date: transaction.date,
            notes: transaction.notes,
            account: transaction.account,
            emoji: transaction.emoji,
            recurring: transaction.recurring,
            isAutoGenerated: transaction.isAutoGenerated,
            parentRecurringId: transaction.parentRecurringId,
          })))

        if (error) throw error
      }

      for (const template of templateUpdates) {
        const { error } = await supabase
          .from('transactions')
          .update({ recurring: serializeRecurring(template.recurring) })
          .eq('id', template.id)
          .eq('user_id', userId)

        if (error) throw error
      }
    } catch {
      setTransactions(sortTransactions(source))
    } finally {
      recurringSyncRef.current = false
    }
  }, [userId])

  const fetchTransactions = useCallback(async () => {
    if (!userId) return
    setIsLoading(true)
    try {
      const { data, error } = await supabase
        .from('transactions')
        .select('*')
        .eq('user_id', userId)
        .order('date', { ascending: false })
        .limit(500)
      if (error) throw error
      const mapped = (data ?? []).map(rowToTransaction)
      setTransactions(mapped)
      void syncRecurringTransactions(mapped)
    } catch {
      // offline or DB error — keep whatever is in state
    } finally {
      setIsLoading(false)
    }
  }, [userId, syncRecurringTransactions])

  // ── Fetch budget ──
  const fetchBudget = useCallback(async () => {
    if (!userId) return
    try {
      const { data } = await supabase
        .from('budgets')
        .select('*')
        .eq('user_id', userId)
        .maybeSingle()
      setBudgetState(data ? rowToBudget(data as Record<string, unknown>) : null)
    } catch {
      // keep existing state
    }
  }, [userId])

  // ── Initial load + realtime subscription ──
  useEffect(() => {
    if (!userId) {
      setIsLoading(false)
      return
    }
    fetchTransactions()
    fetchBudget()

    const channel = supabase
      .channel(`transactions-${userId}`)
      .on(
        'postgres_changes',
        { event: '*', schema: 'public', table: 'transactions', filter: `user_id=eq.${userId}` },
        () => { fetchTransactions() }
      )
      .subscribe()

    return () => { supabase.removeChannel(channel) }
  }, [userId, fetchTransactions, fetchBudget])

  // ── Set budget (optimistic + persist) ──
  const setBudget = useCallback((b: Budget | null) => {
    setBudgetState(b)
    resetBudgetThresholds()
    if (!userId) return

    if (b === null) {
      supabase.from('budgets').delete().eq('user_id', userId).then()
    } else {
      supabase.from('budgets').upsert(
        {
          user_id: userId,
          amount: b.amount,
          period: b.period,
          period_start_day: b.period_start_day,
          alert_threshold: b.alert_threshold,
          alert_fired_at: b.alert_fired_at?.toISOString() ?? null,
          notifications_enabled: b.notifications_enabled,
          count_income: b.count_income,
          rollover_enabled: b.rollover_enabled,
        },
        { onConflict: 'user_id' }
      ).then()
    }
  }, [userId, resetBudgetThresholds])

  // ── Add transaction ──
  const addTransaction = useCallback(async (t: Omit<Transaction, 'id' | 'createdAt'>) => {
    if (!userId) return
    const recurring = isRecurringFrequency(t.frequency)
      ? createRecurringConfig(t.frequency, t.date, t.recurring)
      : undefined
    const payload: Omit<Transaction, 'id' | 'createdAt'> = {
      ...t,
      recurring,
      isAutoGenerated: t.isAutoGenerated ?? false,
      parentRecurringId: t.parentRecurringId,
    }
    const optimistic: Transaction = { ...payload, id: `opt-${Date.now()}`, createdAt: new Date() }

    setTransactions((prev) => {
      const updated = [optimistic, ...prev]
      setTimeout(() => { void checkRealtimeTriggers(optimistic, updated) }, 0)
      return updated
    })

    let result = await supabase
      .from('transactions')
      .insert(transactionToInsertRow(userId, payload))
      .select()
      .single()

    if (result.error && isMissingRecurringSchemaError(result.error)) {
      result = await supabase
        .from('transactions')
        .insert(transactionToLegacyInsertRow(userId, payload))
        .select()
        .single()
    }

    const { data, error } = result

    if (error || !data) {
      console.error('[addTransaction] Supabase error:', error)
      setTransactions((prev) => prev.filter((x) => x.id !== optimistic.id))
      throw error
    }

    setTransactions((prev) =>
      prev.map((x) => x.id === optimistic.id ? rowToTransaction(data as Record<string, unknown>) : x)
    )
  }, [userId, checkRealtimeTriggers])

  // ── Delete transaction (with undo window) ──
  const deleteTransaction = useCallback(async (id: string, mode: 'single' | 'stop-recurring' = 'single') => {
    const target = transactions.find((t) => t.id === id)
    if (!target) return

    if (mode === 'stop-recurring' && target.parentRecurringId) {
      const template = transactions.find((item) => item.recurring?.id === target.parentRecurringId)
      setTransactions((prev) => prev.filter((t) => t.id !== id).map((item) => (
        item.id === template?.id
          ? { ...item, frequency: 'none', recurring: undefined }
          : item
      )))

      const templateUpdate = template
        ? supabase
            .from('transactions')
            .update({ frequency: 'none', recurring: null })
            .eq('id', template.id)
            .eq('user_id', userId)
        : Promise.resolve({ error: null })

      const [{ error: deleteError }, { error: updateError }] = await Promise.all([
        supabase.from('transactions').delete().eq('id', id).eq('user_id', userId),
        templateUpdate,
      ])

      if (deleteError || updateError) {
        await fetchTransactions()
        throw deleteError ?? updateError
      }
      return
    }

    setTransactions((prev) => prev.filter((t) => t.id !== id))
    setPendingDeletion({ transaction: target, expiresAt: Date.now() + UNDO_WINDOW_MS })

    // Clear any previous timers
    if (undoTimerRef.current) window.clearTimeout(undoTimerRef.current)
    if (pendingDeleteRef.current) window.clearTimeout(pendingDeleteRef.current.timer)

    // After undo window: actually delete from Supabase
    const deleteTimer = window.setTimeout(async () => {
      setPendingDeletion(null)
      await supabase.from('transactions').delete().eq('id', id)
    }, UNDO_WINDOW_MS)

    pendingDeleteRef.current = { id, timer: deleteTimer }
    undoTimerRef.current = window.setTimeout(() => setPendingDeletion(null), UNDO_WINDOW_MS)
  }, [transactions, userId, fetchTransactions])

  // ── Undo delete ──
  const undoDelete = useCallback(() => {
    if (!pendingDeletion) return
    const t = pendingDeletion.transaction
    setTransactions((prev) => [t, ...prev].sort((a, b) => b.date.getTime() - a.date.getTime()))
    setPendingDeletion(null)
    if (undoTimerRef.current) window.clearTimeout(undoTimerRef.current)
    if (pendingDeleteRef.current) {
      window.clearTimeout(pendingDeleteRef.current.timer)
      pendingDeleteRef.current = null
    }
  }, [pendingDeletion])

  // ── Update transaction ──
  const updateTransaction = useCallback(async (
    id: string,
    updates: Partial<Transaction>,
    scope: 'single' | 'future' = 'single'
  ) => {
    const target = transactions.find((t) => t.id === id)
    if (!target) return

    if (target.recurring && !target.isAutoGenerated && scope === 'single') {
      const recurring = target.recurring
      const nextTemplateDate = getNextDate(target.date, recurring)
      const standalone: Transaction = {
        ...target,
        ...updates,
        recurring: undefined,
        frequency: 'none',
        isAutoGenerated: false,
        parentRecurringId: undefined,
      }
      const futureTemplate: Transaction = {
        ...cloneTransaction(target),
        id: `tpl-${Date.now()}`,
        date: nextTemplateDate,
        createdAt: new Date(),
        recurring: {
          ...recurring,
          lastGeneratedAt: target.date.toISOString(),
        },
      }

      setTransactions((prev) => sortTransactions(
        prev
          .filter((item) => item.id !== id)
          .concat([standalone, futureTemplate])
      ))

      const [updateResult, insertResult] = await Promise.all([
        supabase
          .from('transactions')
          .update(transactionUpdatesToRow({
            ...updates,
            frequency: 'none',
            recurring: undefined,
            isAutoGenerated: false,
            parentRecurringId: undefined,
          }))
          .eq('id', id)
          .eq('user_id', userId),
        supabase
          .from('transactions')
          .insert(transactionToInsertRow(userId!, {
            name: futureTemplate.name,
            amount: futureTemplate.amount,
            type: futureTemplate.type,
            category: futureTemplate.category,
            frequency: futureTemplate.frequency,
            date: futureTemplate.date,
            notes: futureTemplate.notes,
            account: futureTemplate.account,
            emoji: futureTemplate.emoji,
            recurring: futureTemplate.recurring,
            isAutoGenerated: futureTemplate.isAutoGenerated,
            parentRecurringId: futureTemplate.parentRecurringId,
          })),
      ])

      if (updateResult.error || insertResult.error) {
        await fetchTransactions()
        throw updateResult.error ?? insertResult.error
      }

      return
    }

    const nextFrequency = updates.frequency ?? target.frequency
    const normalizedRecurring = target.recurring
      ? (
          nextFrequency === 'none'
            ? undefined
            : createRecurringConfig(nextFrequency as Exclude<Frequency, 'none'>, target.date, {
                ...target.recurring,
                frequency: nextFrequency as Exclude<Frequency, 'none'>,
              })
        )
      : (
          scope === 'future' && isRecurringFrequency(nextFrequency)
            ? createRecurringConfig(nextFrequency, target.date)
            : target.recurring
        )

    const normalizedUpdates: Partial<Transaction> = {
      ...updates,
      recurring: normalizedRecurring,
      frequency: normalizedRecurring ? normalizedRecurring.frequency : nextFrequency,
    }

    setTransactions((prev) => prev.map((t) => t.id === id ? { ...t, ...normalizedUpdates } : t))

    const { error } = await supabase
      .from('transactions')
      .update(transactionUpdatesToRow(normalizedUpdates))
      .eq('id', id)
      .eq('user_id', userId)

    if (error) {
      await fetchTransactions()
      throw error
    }
  }, [transactions, userId, fetchTransactions])

  const balance = transactions.reduce(
    (acc, t) => acc + (t.type === 'income' ? t.amount : -t.amount), 0
  )

  return (
    <ExpenseContext.Provider value={{
      transactions, budget, setBudget, balance,
      isLoading, isOffline,
      addTransaction, deleteTransaction, updateTransaction, fetchTransactions,
      pendingDeletion, undoDelete,
      insights, activeInsights, dismissInsight, checkRealtimeTriggers,
    }}>
      {children}
    </ExpenseContext.Provider>
  )
}

export function useExpense(): ExpenseContextType {
  const ctx = useContext(ExpenseContext)
  if (!ctx) throw new Error('useExpense must be used inside ExpenseProvider')
  return ctx
}
